# Define all 10 locations with their details exactly as you provided
locations = [
    {
        "key": "Wilkins Building",
        "location": {"lat": 51.52576864, "lng": -0.1337191997},
        "img_path": "src/images/wilkins.jpg",
        "trivia_question": "What architectural style is the Wilkins Building primarily known for?",
        "trivia_opt1": "Gothic Revival",
        "trivia_opt2": "Baroque",
        "trivia_opt3": "Art Deco",
        "trivia_answer": "Neo-Grecian",
    },
    {
        "key": "Roberts Building",
        "location": {"lat": 51.5235697, "lng": -0.1320058034},
        "img_path": "src/images/roberts.jpeg",
        "trivia_question": "Who is the Roberts Building likely named after?",
        "trivia_opt1": "A famous writer",
        "trivia_opt2": "A famous architect",
        "trivia_opt3": "A philanthropic donor",
        "trivia_answer": "A pioneering engineer or scientist",
    },
    {
        "key": "Cruciform Building",
        "location": {"lat": 51.52498933, "lng": -0.1350316495},
        "img_path": "src/images/cruciform.jpg",
        "trivia_question": 'What does the "Cruciform" in Cruciform Building likely refer to?',
        "trivia_opt1": "Its role in teaching medieval history",
        "trivia_opt2": "Its association with religious studies",
        "trivia_opt3": "Its original use as a hospital",
        "trivia_answer": "Its architectural shape resembling a cross",
    },
    {
        "key": "Chadwick Building",
        "location": {"lat": 51.52461436, "lng": -0.1345569875},
        "img_path": "src/images/chadwick.jpg",
        "trivia_question": "The Chadwick Building plays a role in which of UCL’s key research areas?",
        "trivia_opt1": "Life sciences",
        "trivia_opt2": "Built environment",
        "trivia_opt3": "Digital humanities",
        "trivia_answer": "UCL Civil, Environmental & Geomatic Engineering",
    },
    {
        "key": "Bartlett School",
        "location": {"lat": 51.52284695, "lng": -0.1346041558},
        "img_path": "src/images/bartlett.jpeg",
        "trivia_question": "What is the Bartlett School at UCL primarily known for?",
        "trivia_opt1": "Law",
        "trivia_opt2": "Medicine",
        "trivia_opt3": "Business",
        "trivia_answer": "Architecture and Planning",
    },
    {
        "key": "Main Library",
        "location": {"lat": 51.52554427, "lng": -0.1336545807},
        "img_path": "src/images/mainlibrary.jpg",
        "trivia_question": "When was UCL's Main Library officially opened?",
        "trivia_opt1": "1826",
        "trivia_opt2": "1901",
        "trivia_opt3": "1850",
        "trivia_answer": "1911",
    },
    {
        "key": "Science Library",
        "location": {"lat": 51.52365779, "lng": -0.1326453254},
        "img_path": "src/images/science.jpg",
        "trivia_question": "What is the primary focus of the Science Library at UCL?",
        "trivia_opt1": "Humanities",
        "trivia_opt2": "Fine Arts",
        "trivia_opt3": "Law",
        "trivia_answer": "STEM subjects",
    },
    {
        "key": "UCL School of Management",
        "location": {"lat": 51.50505241, "lng": -0.01933966746},
        "img_path": "src/images/som.jpg",
        "trivia_question": "What makes the UCL School of Management’s location in One Canada Square unique?",
        "trivia_opt1": "It has direct access to a historic campus.",
        "trivia_opt2": "It is a purely residential tower.",
        "trivia_opt3": "It shares the building with medical research labs.",
        "trivia_answer": "It is situated in London’s financial district, fostering industry connections.",
    },
    {
        "key": "Student Center",
        "location": {"lat": 51.52549762, "lng": -0.1327704056},
        "img_path": "src/images/studentcentre.jpg",
        "trivia_question": "What sustainability feature is notable in the Student Centre?",
        "trivia_opt1": "Solar-powered elevators",
        "trivia_opt2": "Underground geothermal heating",
        "trivia_opt3": "Passive cooling system",
        "trivia_answer": "Rainwater harvesting",
    },
    {
        "key": "Marshgate",
        "location": {"lat": 51.53772055, "lng": -0.01185885678},
        "img_path": "src/images/marshgate.jpg",
        "trivia_question": "What does the UCL Marshgate building primarily focus on?",
        "trivia_opt1": "Sports science",
        "trivia_opt2": "Law",
        "trivia_opt3": "Fine arts",
        "trivia_answer": "Interdisciplinary research",
    },
]
